# Generated by Django 4.2.4 on 2023-11-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='record',
            new_name='start_date',
        ),
    ]
