# Generated by Django 4.2.4 on 2023-11-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_rename_record_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
