# Generated by Django 4.2.4 on 2023-10-25 08:23

from django.db import migrations, models
import main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(validators=[main_app.validators.validate_age])),
            ],
        ),
    ]
